config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'chats#index'
  get '/chat/:id', to: 'chats#chat', as: 'chat'

  post '/chat/:id', to: 'messages#create', as: 'messages'
  post '/message/:id', to: 'messages#read', as: 'read'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  after_create :sms_notification
  belongs_to :user
  belongs_to :recipient, class_name: "User"

  validates :body, :user, :recipient, presence: true


  def read current_user
    if self.recipient_id == current_user.id
      self.is_read = true
      self.save
      $redis.srem("users:sms_posted:id", current_user.id)
    end
  end

private
  def sms_notification 
    SmsNotificationJob.set(WAIT: 5.minute).perform_later self
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :phone,:presence => true,
                  :numericality => true,
                  :length => { :minimum => 10, :maximum => 15 }

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :phone) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :phone) }
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.where.not(id: current_user.id)
  end

  def chat
    @messages = Message.where("(user_id = :current_user AND recipient_id = :recipient_id) OR (user_id = :recipient_id AND recipient_id = :current_user)",
                                  current_user: current_user,
                                  recipient_id: params[:id]).order("created_at ASC")
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    recipient = User.find(params[:id])
    message = current_user.messages.build message_params
    message.recipient = recipient
    message.save
    MessagesChannel.broadcast_to("#{[params[:id].to_i, current_user.id].sort.join()}#{Rails.application.secrets.cable_key}",
      message: render(partial: "messages/message", locals: {message: message}),
      id: message.id)
  end

  def read
    Message.find(params[:id]).read current_user
  end

private

  def message_params
    params.require(:message).permit(:body, :user, :is_read)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chats/chat.html.erb
<div class="container" id="chat">
  chat with <%= User.find(params[:id]).name %>
  <nav id="messages">
    <%= render @messages %>
  </nav>
  <nav id="chat_form">
    <%= form_for Message.new, remote: true do |form| %>
      <%= form.text_field :body %>
      <%= form.submit "Send" %>
    <% end %>
  </nav>
</div>

app/views/chats/index.html.erb
<div class="container">
    <h1>Chat</h1>

    <ul>
      <% @users.each do |u| %>
        <li id="user_<%= u.id %>" >
          <%= u.name %>
          <%= link_to "chat", chat_path(u) %>
        </li>
      <% end %>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if user_signed_in? %>
          <span>Hello, <%= current_user.name %></span>
          <%= link_to 'Log out', destroy_user_session_path, :method => :delete %>
      <% else %>
          <%= link_to 'Log in', new_user_session_path %> или <%= link_to 'Sign up', new_user_registration_path %>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<p id="<%= message.id %>">
  <i class="author"><%= message.user.name %>:</i>
  <%= message.body %>
  <% message.read current_user %>
  <i class="is_read" float="right"><%= "✓" if message.is_read %></i>
</p>